### ISSUE TITLE
Wrong interruption error

### ISSUE THREAD

**Issue by asciid** [asciid/stepik_scanner#3]
If the parser is stopped in unclear way, later it can't read the position file.

```Traceback (most recent call last):
  File "./parser.py", line 62, in <module>
    position = get_position(posn_file, scan_file)
  File "./parser.py", line 19, in get_position
    if content[0] in ('\n', '', ' '):
IndexError: list index out of range
```

Gotta think.

**Comment by asciid** [comment]
If you terminate the program when it works around a file -- file erases.

It can't be fixed but it can be alarmed to the user.
